// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp_ITTciq2g-xnZqB6fmzZuX_un2AD5I4',
    appId: '1:341317037003:web:5c890b9c4e3efd29d6e44e',
    messagingSenderId: '341317037003',
    projectId: 'hersphere-3e41a',
    authDomain: 'hersphere-3e41a.firebaseapp.com',
    storageBucket: 'hersphere-3e41a.appspot.com',
    measurementId: 'G-T7VNL3XQ8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBryf8xVcY22us-VT3lKeeeHj7npXU9gRQ',
    appId: '1:341317037003:android:e1073c44af84153ad6e44e',
    messagingSenderId: '341317037003',
    projectId: 'hersphere-3e41a',
    storageBucket: 'hersphere-3e41a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBUmnVbg1VHcGzHYq1Vx3U8kuj2FOXG8I',
    appId: '1:341317037003:ios:544fdb72c95ece7ed6e44e',
    messagingSenderId: '341317037003',
    projectId: 'hersphere-3e41a',
    storageBucket: 'hersphere-3e41a.appspot.com',
    iosClientId: '341317037003-ca656clnvnfs8erg08pqaiq6hj04n7f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBUmnVbg1VHcGzHYq1Vx3U8kuj2FOXG8I',
    appId: '1:341317037003:ios:544fdb72c95ece7ed6e44e',
    messagingSenderId: '341317037003',
    projectId: 'hersphere-3e41a',
    storageBucket: 'hersphere-3e41a.appspot.com',
    iosClientId: '341317037003-ca656clnvnfs8erg08pqaiq6hj04n7f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
